

mybatis:
  mapper-locations: classpath:mapper/*.xml



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: Sakura_336
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/templates/




